#ifndef EEZ_LVGL_UI_SCREENS_H
#define EEZ_LVGL_UI_SCREENS_H

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *main;
    lv_obj_t *channel_box;
    lv_obj_t *current_channel_number;
    lv_obj_t *current_channel_name;
    lv_obj_t *current_channel_color;
    lv_obj_t *maintab;
    lv_obj_t *hometab;
    lv_obj_t *warning;
    lv_obj_t *warning_2;
    lv_obj_t *openx32logo_1;
    lv_obj_t *warning_1;
    lv_obj_t *configtab;
    lv_obj_t *current_channel_source;
    lv_obj_t *current_channel_gain;
    lv_obj_t *current_channel_phantom;
    lv_obj_t *current_channel_invert;
    lv_obj_t *current_channel_pan_bal;
    lv_obj_t *current_channel_volume;
    lv_obj_t *current_channel_mute;
    lv_obj_t *current_channel_gate;
    lv_obj_t *current_channel_comp;
    lv_obj_t *eqtab;
    lv_obj_t *current_channel_eq;
    lv_obj_t *meterstab;
    lv_obj_t *meters_1_8;
    lv_obj_t *meters_1_8__obj1;
    lv_obj_t *meters_1_8__obj1__meter;
    lv_obj_t *meters_1_8__obj1__obj0;
    lv_obj_t *meters_1_8__obj1__fader;
    lv_obj_t *meters_1_8__obj2;
    lv_obj_t *meters_1_8__obj2__meter;
    lv_obj_t *meters_1_8__obj2__obj0;
    lv_obj_t *meters_1_8__obj2__fader;
    lv_obj_t *meters_1_8__obj3;
    lv_obj_t *meters_1_8__obj3__meter;
    lv_obj_t *meters_1_8__obj3__obj0;
    lv_obj_t *meters_1_8__obj3__fader;
    lv_obj_t *meters_1_8__obj4;
    lv_obj_t *meters_1_8__obj4__meter;
    lv_obj_t *meters_1_8__obj4__obj0;
    lv_obj_t *meters_1_8__obj4__fader;
    lv_obj_t *meters_1_8__obj5;
    lv_obj_t *meters_1_8__obj5__meter;
    lv_obj_t *meters_1_8__obj5__obj0;
    lv_obj_t *meters_1_8__obj5__fader;
    lv_obj_t *meters_1_8__obj6;
    lv_obj_t *meters_1_8__obj6__meter;
    lv_obj_t *meters_1_8__obj6__obj0;
    lv_obj_t *meters_1_8__obj6__fader;
    lv_obj_t *meters_1_8__obj7;
    lv_obj_t *meters_1_8__obj7__meter;
    lv_obj_t *meters_1_8__obj7__obj0;
    lv_obj_t *meters_1_8__obj7__fader;
    lv_obj_t *meters_1_8__obj8;
    lv_obj_t *meters_1_8__obj8__meter;
    lv_obj_t *meters_1_8__obj8__obj0;
    lv_obj_t *meters_1_8__obj8__fader;
    lv_obj_t *meters_9_16;
    lv_obj_t *meters_9_16__obj1;
    lv_obj_t *meters_9_16__obj1__meter;
    lv_obj_t *meters_9_16__obj1__obj0;
    lv_obj_t *meters_9_16__obj1__fader;
    lv_obj_t *meters_9_16__obj2;
    lv_obj_t *meters_9_16__obj2__meter;
    lv_obj_t *meters_9_16__obj2__obj0;
    lv_obj_t *meters_9_16__obj2__fader;
    lv_obj_t *meters_9_16__obj3;
    lv_obj_t *meters_9_16__obj3__meter;
    lv_obj_t *meters_9_16__obj3__obj0;
    lv_obj_t *meters_9_16__obj3__fader;
    lv_obj_t *meters_9_16__obj4;
    lv_obj_t *meters_9_16__obj4__meter;
    lv_obj_t *meters_9_16__obj4__obj0;
    lv_obj_t *meters_9_16__obj4__fader;
    lv_obj_t *meters_9_16__obj5;
    lv_obj_t *meters_9_16__obj5__meter;
    lv_obj_t *meters_9_16__obj5__obj0;
    lv_obj_t *meters_9_16__obj5__fader;
    lv_obj_t *meters_9_16__obj6;
    lv_obj_t *meters_9_16__obj6__meter;
    lv_obj_t *meters_9_16__obj6__obj0;
    lv_obj_t *meters_9_16__obj6__fader;
    lv_obj_t *meters_9_16__obj7;
    lv_obj_t *meters_9_16__obj7__meter;
    lv_obj_t *meters_9_16__obj7__obj0;
    lv_obj_t *meters_9_16__obj7__fader;
    lv_obj_t *meters_9_16__obj8;
    lv_obj_t *meters_9_16__obj8__meter;
    lv_obj_t *meters_9_16__obj8__obj0;
    lv_obj_t *meters_9_16__obj8__fader;
    lv_obj_t *meters_17_24;
    lv_obj_t *meters_17_24__obj1;
    lv_obj_t *meters_17_24__obj1__meter;
    lv_obj_t *meters_17_24__obj1__obj0;
    lv_obj_t *meters_17_24__obj1__fader;
    lv_obj_t *meters_17_24__obj2;
    lv_obj_t *meters_17_24__obj2__meter;
    lv_obj_t *meters_17_24__obj2__obj0;
    lv_obj_t *meters_17_24__obj2__fader;
    lv_obj_t *meters_17_24__obj3;
    lv_obj_t *meters_17_24__obj3__meter;
    lv_obj_t *meters_17_24__obj3__obj0;
    lv_obj_t *meters_17_24__obj3__fader;
    lv_obj_t *meters_17_24__obj4;
    lv_obj_t *meters_17_24__obj4__meter;
    lv_obj_t *meters_17_24__obj4__obj0;
    lv_obj_t *meters_17_24__obj4__fader;
    lv_obj_t *meters_17_24__obj5;
    lv_obj_t *meters_17_24__obj5__meter;
    lv_obj_t *meters_17_24__obj5__obj0;
    lv_obj_t *meters_17_24__obj5__fader;
    lv_obj_t *meters_17_24__obj6;
    lv_obj_t *meters_17_24__obj6__meter;
    lv_obj_t *meters_17_24__obj6__obj0;
    lv_obj_t *meters_17_24__obj6__fader;
    lv_obj_t *meters_17_24__obj7;
    lv_obj_t *meters_17_24__obj7__meter;
    lv_obj_t *meters_17_24__obj7__obj0;
    lv_obj_t *meters_17_24__obj7__fader;
    lv_obj_t *meters_17_24__obj8;
    lv_obj_t *meters_17_24__obj8__meter;
    lv_obj_t *meters_17_24__obj8__obj0;
    lv_obj_t *meters_17_24__obj8__fader;
    lv_obj_t *meters_25_32;
    lv_obj_t *meters_25_32__obj1;
    lv_obj_t *meters_25_32__obj1__meter;
    lv_obj_t *meters_25_32__obj1__obj0;
    lv_obj_t *meters_25_32__obj1__fader;
    lv_obj_t *meters_25_32__obj2;
    lv_obj_t *meters_25_32__obj2__meter;
    lv_obj_t *meters_25_32__obj2__obj0;
    lv_obj_t *meters_25_32__obj2__fader;
    lv_obj_t *meters_25_32__obj3;
    lv_obj_t *meters_25_32__obj3__meter;
    lv_obj_t *meters_25_32__obj3__obj0;
    lv_obj_t *meters_25_32__obj3__fader;
    lv_obj_t *meters_25_32__obj4;
    lv_obj_t *meters_25_32__obj4__meter;
    lv_obj_t *meters_25_32__obj4__obj0;
    lv_obj_t *meters_25_32__obj4__fader;
    lv_obj_t *meters_25_32__obj5;
    lv_obj_t *meters_25_32__obj5__meter;
    lv_obj_t *meters_25_32__obj5__obj0;
    lv_obj_t *meters_25_32__obj5__fader;
    lv_obj_t *meters_25_32__obj6;
    lv_obj_t *meters_25_32__obj6__meter;
    lv_obj_t *meters_25_32__obj6__obj0;
    lv_obj_t *meters_25_32__obj6__fader;
    lv_obj_t *meters_25_32__obj7;
    lv_obj_t *meters_25_32__obj7__meter;
    lv_obj_t *meters_25_32__obj7__obj0;
    lv_obj_t *meters_25_32__obj7__fader;
    lv_obj_t *meters_25_32__obj8;
    lv_obj_t *meters_25_32__obj8__meter;
    lv_obj_t *meters_25_32__obj8__obj0;
    lv_obj_t *meters_25_32__obj8__fader;
    lv_obj_t *meters_aux;
    lv_obj_t *meters_aux__obj1;
    lv_obj_t *meters_aux__obj1__meter;
    lv_obj_t *meters_aux__obj1__obj0;
    lv_obj_t *meters_aux__obj1__fader;
    lv_obj_t *meters_aux__obj2;
    lv_obj_t *meters_aux__obj2__meter;
    lv_obj_t *meters_aux__obj2__obj0;
    lv_obj_t *meters_aux__obj2__fader;
    lv_obj_t *meters_aux__obj3;
    lv_obj_t *meters_aux__obj3__meter;
    lv_obj_t *meters_aux__obj3__obj0;
    lv_obj_t *meters_aux__obj3__fader;
    lv_obj_t *meters_aux__obj4;
    lv_obj_t *meters_aux__obj4__meter;
    lv_obj_t *meters_aux__obj4__obj0;
    lv_obj_t *meters_aux__obj4__fader;
    lv_obj_t *meters_aux__obj5;
    lv_obj_t *meters_aux__obj5__meter;
    lv_obj_t *meters_aux__obj5__obj0;
    lv_obj_t *meters_aux__obj5__fader;
    lv_obj_t *meters_aux__obj6;
    lv_obj_t *meters_aux__obj6__meter;
    lv_obj_t *meters_aux__obj6__obj0;
    lv_obj_t *meters_aux__obj6__fader;
    lv_obj_t *meters_aux__obj7;
    lv_obj_t *meters_aux__obj7__meter;
    lv_obj_t *meters_aux__obj7__obj0;
    lv_obj_t *meters_aux__obj7__fader;
    lv_obj_t *meters_aux__obj8;
    lv_obj_t *meters_aux__obj8__meter;
    lv_obj_t *meters_aux__obj8__obj0;
    lv_obj_t *meters_aux__obj8__fader;
    lv_obj_t *meters_fxret;
    lv_obj_t *meters_fxret__obj1;
    lv_obj_t *meters_fxret__obj1__meter;
    lv_obj_t *meters_fxret__obj1__obj0;
    lv_obj_t *meters_fxret__obj1__fader;
    lv_obj_t *meters_fxret__obj2;
    lv_obj_t *meters_fxret__obj2__meter;
    lv_obj_t *meters_fxret__obj2__obj0;
    lv_obj_t *meters_fxret__obj2__fader;
    lv_obj_t *meters_fxret__obj3;
    lv_obj_t *meters_fxret__obj3__meter;
    lv_obj_t *meters_fxret__obj3__obj0;
    lv_obj_t *meters_fxret__obj3__fader;
    lv_obj_t *meters_fxret__obj4;
    lv_obj_t *meters_fxret__obj4__meter;
    lv_obj_t *meters_fxret__obj4__obj0;
    lv_obj_t *meters_fxret__obj4__fader;
    lv_obj_t *meters_fxret__obj5;
    lv_obj_t *meters_fxret__obj5__meter;
    lv_obj_t *meters_fxret__obj5__obj0;
    lv_obj_t *meters_fxret__obj5__fader;
    lv_obj_t *meters_fxret__obj6;
    lv_obj_t *meters_fxret__obj6__meter;
    lv_obj_t *meters_fxret__obj6__obj0;
    lv_obj_t *meters_fxret__obj6__fader;
    lv_obj_t *meters_fxret__obj7;
    lv_obj_t *meters_fxret__obj7__meter;
    lv_obj_t *meters_fxret__obj7__obj0;
    lv_obj_t *meters_fxret__obj7__fader;
    lv_obj_t *meters_fxret__obj8;
    lv_obj_t *meters_fxret__obj8__meter;
    lv_obj_t *meters_fxret__obj8__obj0;
    lv_obj_t *meters_fxret__obj8__fader;
    lv_obj_t *meters_bus_1_8;
    lv_obj_t *meters_bus_1_8__obj1;
    lv_obj_t *meters_bus_1_8__obj1__meter;
    lv_obj_t *meters_bus_1_8__obj1__obj0;
    lv_obj_t *meters_bus_1_8__obj1__fader;
    lv_obj_t *meters_bus_1_8__obj2;
    lv_obj_t *meters_bus_1_8__obj2__meter;
    lv_obj_t *meters_bus_1_8__obj2__obj0;
    lv_obj_t *meters_bus_1_8__obj2__fader;
    lv_obj_t *meters_bus_1_8__obj3;
    lv_obj_t *meters_bus_1_8__obj3__meter;
    lv_obj_t *meters_bus_1_8__obj3__obj0;
    lv_obj_t *meters_bus_1_8__obj3__fader;
    lv_obj_t *meters_bus_1_8__obj4;
    lv_obj_t *meters_bus_1_8__obj4__meter;
    lv_obj_t *meters_bus_1_8__obj4__obj0;
    lv_obj_t *meters_bus_1_8__obj4__fader;
    lv_obj_t *meters_bus_1_8__obj5;
    lv_obj_t *meters_bus_1_8__obj5__meter;
    lv_obj_t *meters_bus_1_8__obj5__obj0;
    lv_obj_t *meters_bus_1_8__obj5__fader;
    lv_obj_t *meters_bus_1_8__obj6;
    lv_obj_t *meters_bus_1_8__obj6__meter;
    lv_obj_t *meters_bus_1_8__obj6__obj0;
    lv_obj_t *meters_bus_1_8__obj6__fader;
    lv_obj_t *meters_bus_1_8__obj7;
    lv_obj_t *meters_bus_1_8__obj7__meter;
    lv_obj_t *meters_bus_1_8__obj7__obj0;
    lv_obj_t *meters_bus_1_8__obj7__fader;
    lv_obj_t *meters_bus_1_8__obj8;
    lv_obj_t *meters_bus_1_8__obj8__meter;
    lv_obj_t *meters_bus_1_8__obj8__obj0;
    lv_obj_t *meters_bus_1_8__obj8__fader;
    lv_obj_t *meters_bus_9_16;
    lv_obj_t *meters_bus_9_16__obj1;
    lv_obj_t *meters_bus_9_16__obj1__meter;
    lv_obj_t *meters_bus_9_16__obj1__obj0;
    lv_obj_t *meters_bus_9_16__obj1__fader;
    lv_obj_t *meters_bus_9_16__obj2;
    lv_obj_t *meters_bus_9_16__obj2__meter;
    lv_obj_t *meters_bus_9_16__obj2__obj0;
    lv_obj_t *meters_bus_9_16__obj2__fader;
    lv_obj_t *meters_bus_9_16__obj3;
    lv_obj_t *meters_bus_9_16__obj3__meter;
    lv_obj_t *meters_bus_9_16__obj3__obj0;
    lv_obj_t *meters_bus_9_16__obj3__fader;
    lv_obj_t *meters_bus_9_16__obj4;
    lv_obj_t *meters_bus_9_16__obj4__meter;
    lv_obj_t *meters_bus_9_16__obj4__obj0;
    lv_obj_t *meters_bus_9_16__obj4__fader;
    lv_obj_t *meters_bus_9_16__obj5;
    lv_obj_t *meters_bus_9_16__obj5__meter;
    lv_obj_t *meters_bus_9_16__obj5__obj0;
    lv_obj_t *meters_bus_9_16__obj5__fader;
    lv_obj_t *meters_bus_9_16__obj6;
    lv_obj_t *meters_bus_9_16__obj6__meter;
    lv_obj_t *meters_bus_9_16__obj6__obj0;
    lv_obj_t *meters_bus_9_16__obj6__fader;
    lv_obj_t *meters_bus_9_16__obj7;
    lv_obj_t *meters_bus_9_16__obj7__meter;
    lv_obj_t *meters_bus_9_16__obj7__obj0;
    lv_obj_t *meters_bus_9_16__obj7__fader;
    lv_obj_t *meters_bus_9_16__obj8;
    lv_obj_t *meters_bus_9_16__obj8__meter;
    lv_obj_t *meters_bus_9_16__obj8__obj0;
    lv_obj_t *meters_bus_9_16__obj8__fader;
    lv_obj_t *meters_matrix;
    lv_obj_t *meters_matrix__obj1;
    lv_obj_t *meters_matrix__obj1__meter;
    lv_obj_t *meters_matrix__obj1__obj0;
    lv_obj_t *meters_matrix__obj1__fader;
    lv_obj_t *meters_matrix__obj2;
    lv_obj_t *meters_matrix__obj2__meter;
    lv_obj_t *meters_matrix__obj2__obj0;
    lv_obj_t *meters_matrix__obj2__fader;
    lv_obj_t *meters_matrix__obj3;
    lv_obj_t *meters_matrix__obj3__meter;
    lv_obj_t *meters_matrix__obj3__obj0;
    lv_obj_t *meters_matrix__obj3__fader;
    lv_obj_t *meters_matrix__obj4;
    lv_obj_t *meters_matrix__obj4__meter;
    lv_obj_t *meters_matrix__obj4__obj0;
    lv_obj_t *meters_matrix__obj4__fader;
    lv_obj_t *meters_matrix__obj5;
    lv_obj_t *meters_matrix__obj5__meter;
    lv_obj_t *meters_matrix__obj5__obj0;
    lv_obj_t *meters_matrix__obj5__fader;
    lv_obj_t *meters_matrix__obj6;
    lv_obj_t *meters_matrix__obj6__meter;
    lv_obj_t *meters_matrix__obj6__obj0;
    lv_obj_t *meters_matrix__obj6__fader;
    lv_obj_t *meters_matrix__obj7;
    lv_obj_t *meters_matrix__obj7__meter;
    lv_obj_t *meters_matrix__obj7__obj0;
    lv_obj_t *meters_matrix__obj7__fader;
    lv_obj_t *meters_matrix__obj8;
    lv_obj_t *meters_matrix__obj8__meter;
    lv_obj_t *meters_matrix__obj8__obj0;
    lv_obj_t *meters_matrix__obj8__fader;
    lv_obj_t *ms_main_lr;
    lv_obj_t *ms_main_lr__meter;
    lv_obj_t *ms_main_lr__obj0;
    lv_obj_t *ms_main_lr__fader;
    lv_obj_t *configtab_1;
    lv_obj_t *rta_chart;
    lv_obj_t *routingtab;
    lv_obj_t *hw_inputs;
    lv_obj_t *hw_outputs;
    lv_obj_t *fpga;
    lv_obj_t *mixer;
    lv_obj_t *routing_input;
    lv_obj_t *routing_input_1;
    lv_obj_t *dsp;
    lv_obj_t *table_routing_fpga_header;
    lv_obj_t *table_routing_fpga;
    lv_obj_t *table_routing_dsp_input_header;
    lv_obj_t *table_routing_dsp_input;
    lv_obj_t *table_routing_dsp_output_header;
    lv_obj_t *table_routing_dsp_output;
    lv_obj_t *setuptab;
    lv_obj_t *setup_card_detected;
    lv_obj_t *setup_card_channelmode;
    lv_obj_t *fxtable;
    lv_obj_t *testbar;
    lv_obj_t *testbartext;
    lv_obj_t *debugtext_dsp1;
    lv_obj_t *debugtext_dsp2;
    lv_obj_t *debugtext_x32ctrl;
    lv_obj_t *display_encoder_sliders;
    lv_obj_t *widget1;
    lv_obj_t *widget1__label;
    lv_obj_t *widget1__value;
    lv_obj_t *widget1__slider;
    lv_obj_t *widget1__label_buttonpress;
    lv_obj_t *widget2;
    lv_obj_t *widget2__label;
    lv_obj_t *widget2__value;
    lv_obj_t *widget2__slider;
    lv_obj_t *widget2__label_buttonpress;
    lv_obj_t *widget3;
    lv_obj_t *widget3__label;
    lv_obj_t *widget3__value;
    lv_obj_t *widget3__slider;
    lv_obj_t *widget3__label_buttonpress;
    lv_obj_t *widget4;
    lv_obj_t *widget4__label;
    lv_obj_t *widget4__value;
    lv_obj_t *widget4__slider;
    lv_obj_t *widget4__label_buttonpress;
    lv_obj_t *widget5;
    lv_obj_t *widget5__label;
    lv_obj_t *widget5__value;
    lv_obj_t *widget5__slider;
    lv_obj_t *widget5__label_buttonpress;
    lv_obj_t *widget6;
    lv_obj_t *widget6__label;
    lv_obj_t *widget6__value;
    lv_obj_t *widget6__slider;
    lv_obj_t *widget6__label_buttonpress;
    lv_obj_t *bodyless_instructions;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_MAIN = 1,
};

void create_screen_main();
void tick_screen_main();

void create_user_widget_8meters(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_8meters(int startWidgetIndex);

void create_user_widget_meter_strip(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_meter_strip(int startWidgetIndex);

void create_user_widget_ms_bar(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_ms_bar(int startWidgetIndex);

void create_user_widget_ms_bar8(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_ms_bar8(int startWidgetIndex);

void create_user_widget_config_slider_display_encoder(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_config_slider_display_encoder(int startWidgetIndex);

void create_user_widget_config_slider(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_config_slider(int startWidgetIndex);

void create_user_widget_widget_fx(lv_obj_t *parent_obj, int startWidgetIndex);
void tick_user_widget_widget_fx(int startWidgetIndex);

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_SCREENS_H*/