#pragma once


typedef enum  {
    X32_BTN_NONE,

    //###########################################
    //#
    //#    Board Main
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#    - X32 Rack
    //#    - X32 Core
    //#
    //###########################################

    // Only X32 Core
    X32_BTN_SCENE_SETUP,

    // Only X32 Rack
    X32_BTN_CHANNEL_SOLO,
    X32_BTN_CHANNEL_MUTE,
    X32_BTN_CHANNEL_ENCODER,

    X32_BTN_TALK_A,
    X32_BTN_TALK_B,
    X32_BTN_VIEW_TALK,
    X32_BTN_MONITOR_DIM,
    X32_BTN_VIEW_MONITOR,

    X32_BTN_VIEW_USB,

    X32_BTN_PHANTOM_48V,
    X32_BTN_PHASE_INVERT,
    X32_BTN_LOW_CUT,
    X32_BTN_VIEW_CONFIG,

    X32_BTN_GATE,
    X32_BTN_VIEW_GATE,

    X32_BTN_COMPRESSOR,
    X32_BTN_VIEW_COMPRESSOR,

    X32_BTN_EQ,
    X32_BTN_EQ_MODE,
    X32_BTN_EQ_HIGH,
    X32_BTN_EQ_HIGH_MID,
    X32_BTN_EQ_LOW_MID,
    X32_BTN_EQ_LOW,
    X32_BTN_VIEW_EQ,

    X32_BTN_VIEW_MIX_BUS_SENDS,
    X32_BTN_MONO_BUS,
    X32_BTN_MAIN_LR_BUS,
    X32_BTN_VIEW_BUS_MIXES,
    X32_BTN_BUS_SEND_1_4,
    X32_BTN_BUS_SEND_5_8,
    X32_BTN_BUS_SEND_9_12,
    X32_BTN_BUS_SEND_13_16,

    X32_BTN_ENCODER1,
    X32_BTN_ENCODER2,
    X32_BTN_ENCODER3,
    X32_BTN_ENCODER4,
    X32_BTN_ENCODER5,
    X32_BTN_ENCODER6,

    X32_BTN_HOME,
    X32_BTN_METERS,
    X32_BTN_ROUTING,
    X32_BTN_SETUP,
    X32_BTN_LIBRARY,
    X32_BTN_EFFECTS,
    X32_BTN_MUTE_GRP,
    X32_BTN_UTILITY,

    X32_BTN_UP,
    X32_BTN_DOWN,
    X32_BTN_LEFT,
    X32_BTN_RIGHT,

    //###########################################
    //#
    //#    Board L
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#
    //###########################################

    // X32 Full
    X32_BTN_CH_1_16,
    X32_BTN_CH_17_32,
    X32_BTN_AUX_IN_EFFECTS,
    X32_BTN_EFFECTS_RETURNS,
    X32_BTN_BUS_MASTER,
    // X32 Compact/Producer
    X32_BTN_CH_1_8,
    X32_BTN_CH_9_16,
    X32_BTN_CH_17_24,
    X32_BTN_CH_25_32,
    X32_BTN_AUX_IN_1_6_USB_REC,
    X32_BTN_BUS_1_8_MASTER,
    X32_BTN_BUS_9_16_MASTER,

    X32_BTN_BOARD_L_CH_1_SELECT,
    X32_BTN_BOARD_L_CH_2_SELECT,
    X32_BTN_BOARD_L_CH_3_SELECT,
    X32_BTN_BOARD_L_CH_4_SELECT,
    X32_BTN_BOARD_L_CH_5_SELECT,
    X32_BTN_BOARD_L_CH_6_SELECT,
    X32_BTN_BOARD_L_CH_7_SELECT,
    X32_BTN_BOARD_L_CH_8_SELECT,

    X32_BTN_BOARD_L_CH_1_SOLO,
    X32_BTN_BOARD_L_CH_2_SOLO,
    X32_BTN_BOARD_L_CH_3_SOLO,
    X32_BTN_BOARD_L_CH_4_SOLO,
    X32_BTN_BOARD_L_CH_5_SOLO,
    X32_BTN_BOARD_L_CH_6_SOLO,
    X32_BTN_BOARD_L_CH_7_SOLO,
    X32_BTN_BOARD_L_CH_8_SOLO,

    X32_BTN_BOARD_L_CH_1_MUTE,
    X32_BTN_BOARD_L_CH_2_MUTE,
    X32_BTN_BOARD_L_CH_3_MUTE,
    X32_BTN_BOARD_L_CH_4_MUTE,
    X32_BTN_BOARD_L_CH_5_MUTE,
    X32_BTN_BOARD_L_CH_6_MUTE,
    X32_BTN_BOARD_L_CH_7_MUTE,
    X32_BTN_BOARD_L_CH_8_MUTE,

    //###########################################
    //#
    //#   Board M
    //#
    //#    - X32 Full
    //#
    //###########################################

    X32_BTN_BOARD_M_CH_1_SELECT,
    X32_BTN_BOARD_M_CH_2_SELECT,
    X32_BTN_BOARD_M_CH_3_SELECT,
    X32_BTN_BOARD_M_CH_4_SELECT,
    X32_BTN_BOARD_M_CH_5_SELECT,
    X32_BTN_BOARD_M_CH_6_SELECT,
    X32_BTN_BOARD_M_CH_7_SELECT,
    X32_BTN_BOARD_M_CH_8_SELECT,

    X32_BTN_BOARD_M_CH_1_SOLO,
    X32_BTN_BOARD_M_CH_2_SOLO,
    X32_BTN_BOARD_M_CH_3_SOLO,
    X32_BTN_BOARD_M_CH_4_SOLO,
    X32_BTN_BOARD_M_CH_5_SOLO,
    X32_BTN_BOARD_M_CH_6_SOLO,
    X32_BTN_BOARD_M_CH_7_SOLO,
    X32_BTN_BOARD_M_CH_8_SOLO,

    X32_BTN_BOARD_M_CH_1_MUTE,
    X32_BTN_BOARD_M_CH_2_MUTE,
    X32_BTN_BOARD_M_CH_3_MUTE,
    X32_BTN_BOARD_M_CH_4_MUTE,
    X32_BTN_BOARD_M_CH_5_MUTE,
    X32_BTN_BOARD_M_CH_6_MUTE,
    X32_BTN_BOARD_M_CH_7_MUTE,
    X32_BTN_BOARD_M_CH_8_MUTE,

    //###########################################
    //#
    //#    Board R
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#
    //###########################################

    X32_BTN_DAW_REMOTE,
    X32_BTN_SEND_ON_FADERS,
    X32_BTN_GROUP_DCA_1_8,
    X32_BTN_BUS_1_8,
    X32_BTN_BUS_9_16,
    X32_BTN_MATRIX_MAIN_C,
    X32_BTN_CLEAR_SOLO,

    X32_BTN_SCENES_UNDO,
    X32_BTN_SCENES_GO,
    X32_BTN_SCENES_PREV,
    X32_BTN_SCENES_NEXT,
    X32_BTN_VIEW_SCENES,

    X32_BTN_ASSIGN_1,
    X32_BTN_ASSIGN_2,
    X32_BTN_ASSIGN_3,
    X32_BTN_ASSIGN_4,
    X32_BTN_ASSIGN_5,
    X32_BTN_ASSIGN_6,
    X32_BTN_ASSIGN_7,
    X32_BTN_ASSIGN_8,
    X32_BTN_VIEW_ASSIGN,

    // Only X32 Full
    X32_BTN_ASSIGN_9,
    X32_BTN_ASSIGN_10,
    X32_BTN_ASSIGN_11,
    X32_BTN_ASSIGN_12,
    X32_BTN_ASSIGN_A,
    X32_BTN_ASSIGN_B,
    X32_BTN_ASSIGN_C, 

    X32_BTN_MUTE_GROUP_1,
    X32_BTN_MUTE_GROUP_2,
    X32_BTN_MUTE_GROUP_3,
    X32_BTN_MUTE_GROUP_4,
    X32_BTN_MUTE_GROUP_5,
    X32_BTN_MUTE_GROUP_6,

    X32_BTN_BOARD_R_CH_1_SELECT,
    X32_BTN_BOARD_R_CH_2_SELECT,
    X32_BTN_BOARD_R_CH_3_SELECT,
    X32_BTN_BOARD_R_CH_4_SELECT,
    X32_BTN_BOARD_R_CH_5_SELECT,
    X32_BTN_BOARD_R_CH_6_SELECT,
    X32_BTN_BOARD_R_CH_7_SELECT,
    X32_BTN_BOARD_R_CH_8_SELECT,
    X32_BTN_MAIN_SELECT,

    X32_BTN_BOARD_R_CH_1_SOLO,
    X32_BTN_BOARD_R_CH_2_SOLO,
    X32_BTN_BOARD_R_CH_3_SOLO,
    X32_BTN_BOARD_R_CH_4_SOLO,
    X32_BTN_BOARD_R_CH_5_SOLO,
    X32_BTN_BOARD_R_CH_6_SOLO,
    X32_BTN_BOARD_R_CH_7_SOLO,
    X32_BTN_BOARD_R_CH_8_SOLO,
    X32_BTN_MAIN_SOLO,

    X32_BTN_BOARD_R_CH_1_MUTE,
    X32_BTN_BOARD_R_CH_2_MUTE,
    X32_BTN_BOARD_R_CH_3_MUTE,
    X32_BTN_BOARD_R_CH_4_MUTE,
    X32_BTN_BOARD_R_CH_5_MUTE,
    X32_BTN_BOARD_R_CH_6_MUTE,
    X32_BTN_BOARD_R_CH_7_MUTE,
    X32_BTN_BOARD_R_CH_8_MUTE,
    X32_BTN_MAIN_MUTE,

    //###########################################
    //#
    //#    LED only
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#    - X32 Core
    //#
    //###########################################

    X32_LED_USB_ACCESS,

    X32_LED_BACKLIGHT_CONFIG_GAIN,
    X32_LED_BACKLIGHT_CONFIG_FREQ,
    X32_LED_BACKLIGHT_GATE_THRESHOLD,
    X32_LED_BACKLIGHT_DYNAMICS_THRESHOLD,
    X32_LED_BACKLIGHT_EQ_Q,
    X32_LED_BACKLIGHT_EQ_FREQ,
    X32_LED_BACKLIGHT_EQ_GAIN,
    X32_LED_BACKLIGHT_BUS_MIXES_LEVEL,
    X32_LED_BACKLIGHT_BUS_MIXES_PAN,

    X32_LED_EQ_HCUT,
    X32_LED_EQ_HSHV,
    X32_LED_EQ_VEQ,
    X32_LED_EQ_PEQ,
    X32_LED_EQ_LSHV,
    X32_LED_EQ_LCUT,

    // X32 Rack only
    X32_LED_VIEW_USB_RED,
    X32_LED_MAIN,
    X32_LED_MATRIX,
    X32_LED_BACKLIGHT_CHANNEL_LEVEL,
    X32_LED_BACKLIGHT_MAIN_LEVEL,

    // X32 Core only
    X32_LED_SCENE_SETUP_RED,
    X32_LED_IN,
    X32_LED_AUX,
    X32_LED_BUS,
    X32_LED_MTX,
    X32_LED_DCA,
    X32_LED_AESA_GREEN,
    X32_LED_AESA_RED,
    X32_LED_AESB_GREEN,
    X32_LED_AESB_RED,

    X32_LED_BACKLIGHT_ASSING_1,
    X32_LED_BACKLIGHT_ASSING_2,
    X32_LED_BACKLIGHT_ASSING_3,
    X32_LED_BACKLIGHT_ASSING_4

} X32_BTN;

typedef enum  {
    X32_ENC_NONE,

    X32_ENC_GAIN,
    X32_ENC_LOWCUT,
    X32_ENC_GATE,
    X32_ENC_DYNAMICS,
    X32_ENC_EQ_Q,
    X32_ENC_EQ_FREQ,
    X32_ENC_EQ_GAIN,
    X32_ENC_MAIN,
    X32_ENC_PAN,

    X32_ENC_BUS_SEND_1,
    X32_ENC_BUS_SEND_2,
    X32_ENC_BUS_SEND_3,
    X32_ENC_BUS_SEND_4,

    X32_ENC_ENCODER1,
    X32_ENC_ENCODER2,
    X32_ENC_ENCODER3,
    X32_ENC_ENCODER4,
    X32_ENC_ENCODER5,
    X32_ENC_ENCODER6,

    // only X32 Full and X32 Core
    X32_ENC_ASSIGN_1,
    // only X32 Full and X32 Core
    X32_ENC_ASSIGN_2,
    // only X32 Full
    X32_ENC_ASSIGN_3,
    // only X32 Full
    X32_ENC_ASSIGN_4,

    // only X32 Rack
    X32_ENC_CHANNEL_SELECT,
    // only X32 Rack
    X32_ENC_CHANNEL_LEVEL,
    // only X32 Rack
    X32_ENC_MAIN_LEVEL,

} X32_ENC;

// Mode of the Banking
typedef enum {
    // Standard Layout like X32 Original
    X32_SURFACE_MODE_BANKING_X32,

    // User Layout
    X32_SURFACE_MODE_BANKING_USER,
} X32_SURFACE_MODE_BANKING;

typedef enum {
    X32_BOARD_MAIN =    0x00,
    X32_BOARD_L =       0x04,
    X32_BOARD_M =       0x05, // only X32 Full
    X32_BOARD_R =       0x08,
} X32_BOARD;

typedef enum {
    X32_MODEL_NONE,
    X32_MODEL_FULL,
    X32_MODEL_COMPACT,
    X32_MODEL_PRODUCER,
    X32_MODEL_RACK,
    X32_MODEL_CORE
} X32_MODEL;

typedef enum {
    X32_PAGE_NONE,
    X32_PAGE_HOME,
        // sub-pages of home
        X32_PAGE_CONFIG,
        X32_PAGE_GATE,
        X32_PAGE_EQ,
        X32_PAGE_COMPRESSOR,
    X32_PAGE_METERS,
        // sub-pages of meters?
    X32_PAGE_ROUTING,
        // sub-pages of routing
        X32_PAGE_ROUTING_FPGA,
        X32_PAGE_ROUTING_DSP1,
        X32_PAGE_ROUTING_DSP2,
    X32_PAGE_SETUP,
        // sub-pages of setup
        X32_PAGE_SETUP_CARD,
    X32_PAGE_LIBRARY,
    X32_PAGE_EFFECTS,
    X32_PAGE_MUTE_GRP,
    X32_PAGE_UTILITY
} X32_PAGE;

typedef enum {
    X32_VCHANNELTYPE_NONE,
    X32_VCHANNELTYPE_NORMAL,
    X32_VCHANNELTYPE_AUX,
    X32_VCHANNELTYPE_FXRET,
    X32_VCHANNELTYPE_BUS,
    X32_VCHANNELTYPE_MATRIX,
    X32_VCHANNELTYPE_DCA,
    X32_VCHANNELTYPE_MAIN,
    X32_VCHANNELTYPE_MAINSUB,
    X32_VCHANNELTYPE_SPECIAL,
} X32_VCHANNELTYPE;

typedef enum {
    X32_VCHANNEL_BLOCK_NONE = -1,
    X32_VCHANNEL_BLOCK_NORMAL = 0,
    X32_VCHANNEL_BLOCK_AUX = 32,
    X32_VCHANNEL_BLOCK_FXRET = 40,
    X32_VCHANNEL_BLOCK_BUS = 48,
    X32_VCHANNEL_BLOCK_MATRIX = 64,
    X32_VCHANNEL_BLOCK_SPECIAL = 70,
    X32_VCHANNEL_BLOCK_MAINSUB = 71,
    X32_VCHANNEL_BLOCK_DCA = 72,
    X32_VCHANNEL_BLOCK_MAIN = 80    
} X32_VCHANNEL_BLOCK;

typedef enum {
    X32_VCHANNEL_BLOCKSIZE_NONE = 0,
    X32_VCHANNEL_BLOCKSIZE_NORMAL = 32,
    X32_VCHANNEL_BLOCKSIZE_AUX = 8,
    X32_VCHANNEL_BLOCKSIZE_FXRET = 8,
    X32_VCHANNEL_BLOCKSIZE_BUS = 16,
    X32_VCHANNEL_BLOCKSIZE_MATRIX = 6,
    X32_VCHANNEL_BLOCKSIZE_DCA = 8,
    X32_VCHANNEL_BLOCKSIZE_MAIN = 1,
    X32_VCHANNEL_BLOCKSIZE_MAINSUB = 1,
    X32_VCHANNEL_BLOCKSIZE_SPECIAL = 1,
} X32_VCHANNEL_BLOCKSIZE;

typedef enum {
    MIXERPARAMETER_UOM_NONE,
    MIXERPARAMETER_UOM_DB, // dB
    MIXERPARAMETER_UOM_DBFS, // dB Full Scale
    MIXERPARAMETER_UOM_MS, // Milliseconds
    MIXERPARAMETER_UOM_SECONDS, // Seconds
    MIXERPARAMETER_UOM_HZ, // Hertz
    MIXERPARAMETER_UOM_KHZ, // Kilohertz
    MIXERPARAMETER_UOM_PERCENT, // Percent
} MIXERPARAMETER_UOM;

typedef enum {
    MIXERPARAMETER_VALUE_TYPE_FLOAT,
    MIXERPARAMETER_VALUE_TYPE_UINT8,
    MIXERPARAMETER_VALUE_TYPE_INT8,

    MIXERPARAMETER_VALUE_TYPE_FLOAT_LIST,
    MIXERPARAMETER_VALUE_TYPE_UINT8_LIST,
    MIXERPARAMETER_VALUE_TYPE_INT8_LIST,
} MIXERPARAMETER_VALUE_TYPE;

typedef enum {
    MIXERPARAMETER_NONE,

    MIXERPARAMETER_CHANNEL_GAIN,
    MIXERPARAMETER_CHANNEL_PANORAMA,
    MIXERPARAMETER_CHANNEL_VOLUME,

    MIXERPARAMETER_GATE_TRESHOLD,
    MIXERPARAMETER_GATE_RANGE,
    MIXERPARAMETER_GATE_ATTACK,
    MIXERPARAMETER_GATE_HOLD,
    MIXERPARAMETER_GATE_RELEASE,
    
    MIXERPARAMETER_DYNAMICS_TRESHOLD,
    MIXERPARAMETER_DYNAMICS_RATIO,
    MIXERPARAMETER_DYNAMICS_MAKEUP,
    MIXERPARAMETER_DYNAMICS_ATTACK,
    MIXERPARAMETER_DYNAMICS_HOLD,
    MIXERPARAMETER_DYNAMICS_RELEASE,

    MIXERPARAMETER_FX_REVERB_ROOMSIZE,
    MIXERPARAMETER_FX_REVERB_RT60,
    MIXERPARAMETER_FX_REVERB_LPFREQ,
    MIXERPARAMETER_FX_REVERB_DRY,
    MIXERPARAMETER_FX_REVERB_WET,

    MIXERPARAMETER_FX_CHORUS_DEPTH_A,
    MIXERPARAMETER_FX_CHORUS_DEPTH_B,
    MIXERPARAMETER_FX_CHORUS_DELAY_A,
    MIXERPARAMETER_FX_CHORUS_DELAY_B,
    MIXERPARAMETER_FX_CHORUS_PHASE_A,
    MIXERPARAMETER_FX_CHORUS_PHASE_B,
    MIXERPARAMETER_FX_CHORUS_FREQ_A,
    MIXERPARAMETER_FX_CHORUS_FREQ_B,
    MIXERPARAMETER_FX_CHORUS_MIX,

    MIXERPARAMETER_FX_TRANSIENTSHAPER_FAST,
    MIXERPARAMETER_FX_TRANSIENTSHAPER_MEDIUM,
    MIXERPARAMETER_FX_TRANSIENTSHAPER_SLOW,
    MIXERPARAMETER_FX_TRANSIENTSHAPER_ATTACK,
    MIXERPARAMETER_FX_TRANSIENTSHAPER_SUSTAIN,
    MIXERPARAMETER_FX_TRANSIENTSHAPER_DELAY,

    MIXERPARAMETER_FX_OVERDRIVE_PREGAIN,
    MIXERPARAMETER_FX_OVERDRIVE_Q,
    MIXERPARAMETER_FX_OVERDRIVE_HPF_INPUTFREQ,
    MIXERPARAMETER_FX_OVERDRIVE_LPF_INPUTFREQ,
    MIXERPARAMETER_FX_OVERDRIVE_LPF_OUTPUTFREQ,

    MIXERPARAMETER_FX_DELAY_DELAY_A,
    MIXERPARAMETER_FX_DELAY_DELAY_B,

    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND1_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND2_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND3_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND4_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_BAND5_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_THRESHOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_RATIO,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_ATTACK,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_HOLD,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_RELEASE,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND1_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND2_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND3_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND4_MAKEUP,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_BAND5_MAKEUP,

    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_FREQ1,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_FREQ2,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_FREQ3,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_L_FREQ4,

    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_FREQ1,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_FREQ2,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_FREQ3,
    MIXERPARAMETER_FX_MULTIBANDCOMPRESOR_R_FREQ4,

    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_TYPE,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_TYPE,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_TYPE,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_FREQ,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_FREQ,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_FREQ,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_STATICGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_STATICGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_STATICGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_MAXDYNGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_MAXDYNGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_MAXDYNGAIN,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_Q,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_Q,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_Q,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_THRESHOLD,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_THRESHOLD,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_THRESHOLD,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_RATIO,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_RATIO,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_RATIO,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_ATTACK,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_ATTACK,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_ATTACK,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND1_RELEASE,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND2_RELEASE,
    MIXERPARAMETER_FX_DYNAMICEQ_BAND3_RELEASE,

    MIXERPARAMETER_LCD_CONTRAST,

    MIXERPARAMETER_LED_BRIGHTNESS,

} MIXERPARAMETER;

typedef enum {
    FX_TYPE_NONE = -1,
    FX_TYPE_REVERB = 0,
    FX_TYPE_CHORUS = 1,
    FX_TYPE_TRANSIENTSHAPER = 2,
    FX_TYPE_OVERDRIVE = 3,
    FX_TYPE_DELAY = 4,
    FX_TYPE_MULTIBANDCOMPRESOR = 5,
    FX_TYPE_DYNAMICEQ = 6
} FX_TYPE;