#pragma once


typedef enum  {
    X32_BTN_NONE,

    //###########################################
    //#
    //#    Board Main
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#    - X32 Rack
    //#    - X32 Core
    //#
    //###########################################

    // Only X32 Core
    X32_BTN_SCENE_SETUP,

    // Only X32 Rack
    X32_BTN_CHANNEL_SOLO,
    X32_BTN_CHANNEL_MUTE,
    X32_BTN_CHANNEL_ENCODER,

    X32_BTN_TALK_A,
    X32_BTN_TALK_B,
    X32_BTN_VIEW_TALK,
    X32_BTN_MONITOR_DIM,
    X32_BTN_VIEW_MONITOR,

    X32_BTN_VIEW_USB,

    X32_BTN_PHANTOM_48V,
    X32_BTN_PHASE_INVERT,
    X32_BTN_LOW_CUT,
    X32_BTN_VIEW_CONFIG,

    X32_BTN_GATE,
    X32_BTN_VIEW_GATE,

    X32_BTN_COMPRESSOR,
    X32_BTN_VIEW_COMPRESSOR,

    X32_BTN_EQ,
    X32_BTN_EQ_MODE,
    X32_BTN_EQ_HIGH,
    X32_BTN_EQ_HIGH_MID,
    X32_BTN_EQ_LOW_MID,
    X32_BTN_EQ_LOW,
    X32_BTN_VIEW_EQ,

    X32_BTN_VIEW_MIX_BUS_SENDS,
    X32_BTN_MONO_BUS,
    X32_BTN_MAIN_LR_BUS,
    X32_BTN_VIEW_BUS_MIXES,
    X32_BTN_BUS_SEND_1_4,
    X32_BTN_BUS_SEND_5_8,
    X32_BTN_BUS_SEND_9_12,
    X32_BTN_BUS_SEND_13_16,

    X32_BTN_ENCODER1,
    X32_BTN_ENCODER2,
    X32_BTN_ENCODER3,
    X32_BTN_ENCODER4,
    X32_BTN_ENCODER5,
    X32_BTN_ENCODER6,

    X32_BTN_HOME,
    X32_BTN_METERS,
    X32_BTN_ROUTING,
    X32_BTN_SETUP,
    X32_BTN_LIBRARY,
    X32_BTN_EFFECTS,
    X32_BTN_MUTE_GRP,
    X32_BTN_UTILITY,

    X32_BTN_UP,
    X32_BTN_DOWN,
    X32_BTN_LEFT,
    X32_BTN_RIGHT,

    //###########################################
    //#
    //#    Board L
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#
    //###########################################

    // X32 Full
    X32_BTN_CH_1_16,
    X32_BTN_CH_17_32,
    X32_BTN_AUX_IN_EFFECTS,
    X32_BTN_EFFECTS_RETURNS,
    X32_BTN_BUS_MASTER,
    // X32 Compact/Producer
    X32_BTN_CH_1_8,
    X32_BTN_CH_9_16,
    X32_BTN_CH_17_24,
    X32_BTN_CH_25_32,
    X32_BTN_AUX_IN_1_6_USB_REC,
    X32_BTN_BUS_1_8_MASTER,
    X32_BTN_BUS_9_16_MASTER,

    X32_BTN_BOARD_L_CH_1_SELECT,
    X32_BTN_BOARD_L_CH_2_SELECT,
    X32_BTN_BOARD_L_CH_3_SELECT,
    X32_BTN_BOARD_L_CH_4_SELECT,
    X32_BTN_BOARD_L_CH_5_SELECT,
    X32_BTN_BOARD_L_CH_6_SELECT,
    X32_BTN_BOARD_L_CH_7_SELECT,
    X32_BTN_BOARD_L_CH_8_SELECT,

    X32_BTN_BOARD_L_CH_1_SOLO,
    X32_BTN_BOARD_L_CH_2_SOLO,
    X32_BTN_BOARD_L_CH_3_SOLO,
    X32_BTN_BOARD_L_CH_4_SOLO,
    X32_BTN_BOARD_L_CH_5_SOLO,
    X32_BTN_BOARD_L_CH_6_SOLO,
    X32_BTN_BOARD_L_CH_7_SOLO,
    X32_BTN_BOARD_L_CH_8_SOLO,

    X32_BTN_BOARD_L_CH_1_MUTE,
    X32_BTN_BOARD_L_CH_2_MUTE,
    X32_BTN_BOARD_L_CH_3_MUTE,
    X32_BTN_BOARD_L_CH_4_MUTE,
    X32_BTN_BOARD_L_CH_5_MUTE,
    X32_BTN_BOARD_L_CH_6_MUTE,
    X32_BTN_BOARD_L_CH_7_MUTE,
    X32_BTN_BOARD_L_CH_8_MUTE,

    //###########################################
    //#
    //#   Board M
    //#
    //#    - X32 Full
    //#
    //###########################################

    X32_BTN_BOARD_M_CH_1_SELECT,
    X32_BTN_BOARD_M_CH_2_SELECT,
    X32_BTN_BOARD_M_CH_3_SELECT,
    X32_BTN_BOARD_M_CH_4_SELECT,
    X32_BTN_BOARD_M_CH_5_SELECT,
    X32_BTN_BOARD_M_CH_6_SELECT,
    X32_BTN_BOARD_M_CH_7_SELECT,
    X32_BTN_BOARD_M_CH_8_SELECT,

    X32_BTN_BOARD_M_CH_1_SOLO,
    X32_BTN_BOARD_M_CH_2_SOLO,
    X32_BTN_BOARD_M_CH_3_SOLO,
    X32_BTN_BOARD_M_CH_4_SOLO,
    X32_BTN_BOARD_M_CH_5_SOLO,
    X32_BTN_BOARD_M_CH_6_SOLO,
    X32_BTN_BOARD_M_CH_7_SOLO,
    X32_BTN_BOARD_M_CH_8_SOLO,

    X32_BTN_BOARD_M_CH_1_MUTE,
    X32_BTN_BOARD_M_CH_2_MUTE,
    X32_BTN_BOARD_M_CH_3_MUTE,
    X32_BTN_BOARD_M_CH_4_MUTE,
    X32_BTN_BOARD_M_CH_5_MUTE,
    X32_BTN_BOARD_M_CH_6_MUTE,
    X32_BTN_BOARD_M_CH_7_MUTE,
    X32_BTN_BOARD_M_CH_8_MUTE,

    //###########################################
    //#
    //#    Board R
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#
    //###########################################

    X32_BTN_DAW_REMOTE,
    X32_BTN_SEND_ON_FADERS,
    X32_BTN_GROUP_DCA_1_8,
    X32_BTN_BUS_1_8,
    X32_BTN_BUS_9_16,
    X32_BTN_MATRIX_MAIN_C,
    X32_BTN_CLEAR_SOLO,

    X32_BTN_SCENES_UNDO,
    X32_BTN_SCENES_GO,
    X32_BTN_SCENES_PREV,
    X32_BTN_SCENES_NEXT,
    X32_BTN_VIEW_SCENES,

    X32_BTN_ASSIGN_1,
    X32_BTN_ASSIGN_2,
    X32_BTN_ASSIGN_3,
    X32_BTN_ASSIGN_4,
    X32_BTN_ASSIGN_5,
    X32_BTN_ASSIGN_6,
    X32_BTN_ASSIGN_7,
    X32_BTN_ASSIGN_8,
    X32_BTN_VIEW_ASSIGN,

    // Only X32 Full
    X32_BTN_ASSIGN_9,
    X32_BTN_ASSIGN_10,
    X32_BTN_ASSIGN_11,
    X32_BTN_ASSIGN_12,
    X32_BTN_ASSIGN_A,
    X32_BTN_ASSIGN_B,
    X32_BTN_ASSIGN_C, 

    X32_BTN_MUTE_GROUP_1,
    X32_BTN_MUTE_GROUP_2,
    X32_BTN_MUTE_GROUP_3,
    X32_BTN_MUTE_GROUP_4,
    X32_BTN_MUTE_GROUP_5,
    X32_BTN_MUTE_GROUP_6,

    X32_BTN_BOARD_R_CH_1_SELECT,
    X32_BTN_BOARD_R_CH_2_SELECT,
    X32_BTN_BOARD_R_CH_3_SELECT,
    X32_BTN_BOARD_R_CH_4_SELECT,
    X32_BTN_BOARD_R_CH_5_SELECT,
    X32_BTN_BOARD_R_CH_6_SELECT,
    X32_BTN_BOARD_R_CH_7_SELECT,
    X32_BTN_BOARD_R_CH_8_SELECT,
    X32_BTN_MAIN_SELECT,

    X32_BTN_BOARD_R_CH_1_SOLO,
    X32_BTN_BOARD_R_CH_2_SOLO,
    X32_BTN_BOARD_R_CH_3_SOLO,
    X32_BTN_BOARD_R_CH_4_SOLO,
    X32_BTN_BOARD_R_CH_5_SOLO,
    X32_BTN_BOARD_R_CH_6_SOLO,
    X32_BTN_BOARD_R_CH_7_SOLO,
    X32_BTN_BOARD_R_CH_8_SOLO,
    X32_BTN_MAIN_SOLO,

    X32_BTN_BOARD_R_CH_1_MUTE,
    X32_BTN_BOARD_R_CH_2_MUTE,
    X32_BTN_BOARD_R_CH_3_MUTE,
    X32_BTN_BOARD_R_CH_4_MUTE,
    X32_BTN_BOARD_R_CH_5_MUTE,
    X32_BTN_BOARD_R_CH_6_MUTE,
    X32_BTN_BOARD_R_CH_7_MUTE,
    X32_BTN_BOARD_R_CH_8_MUTE,
    X32_BTN_MAIN_MUTE,

    //###########################################
    //#
    //#    LED only
    //#
    //#    - X32 Full
    //#    - X32 Compact
    //#    - X32 Producer
    //#    - X32 Core
    //#
    //###########################################

    X32_LED_USB_ACCESS,

    X32_LED_BACKLIGHT_CONFIG_GAIN,
    X32_LED_BACKLIGHT_CONFIG_FREQ,
    X32_LED_BACKLIGHT_GATE_THRESHOLD,
    X32_LED_BACKLIGHT_DYNAMICS_THRESHOLD,
    X32_LED_BACKLIGHT_EQ_Q,
    X32_LED_BACKLIGHT_EQ_FREQ,
    X32_LED_BACKLIGHT_EQ_GAIN,
    X32_LED_BACKLIGHT_BUS_MIXES_LEVEL,
    X32_LED_BACKLIGHT_BUS_MIXES_PAN,

    X32_LED_EQ_HCUT,
    X32_LED_EQ_HSHV,
    X32_LED_EQ_VEQ,
    X32_LED_EQ_PEQ,
    X32_LED_EQ_LSHV,
    X32_LED_EQ_LCUT,

    // X32 Rack only
    X32_LED_VIEW_USB_RED,
    X32_LED_MAIN,
    X32_LED_MATRIX,
    X32_LED_BACKLIGHT_CHANNEL_LEVEL,
    X32_LED_BACKLIGHT_MAIN_LEVEL,

    // X32 Core only
    X32_LED_SCENE_SETUP_RED,
    X32_LED_IN,
    X32_LED_AUX,
    X32_LED_BUS,
    X32_LED_MTX,
    X32_LED_DCA,
    X32_LED_AESA_GREEN,
    X32_LED_AESA_RED,
    X32_LED_AESB_GREEN,
    X32_LED_AESB_RED,

    X32_LED_BACKLIGHT_ASSING_1,
    X32_LED_BACKLIGHT_ASSING_2,
    X32_LED_BACKLIGHT_ASSING_3,
    X32_LED_BACKLIGHT_ASSING_4

} X32_BTN;

typedef enum  {
    X32_ENC_NONE,

    X32_ENC_GAIN,
    X32_ENC_LOWCUT,
    X32_ENC_GATE,
    X32_ENC_DYNAMICS,
    X32_ENC_EQ_Q,
    X32_ENC_EQ_FREQ,
    X32_ENC_EQ_GAIN,
    X32_ENC_MAIN,
    X32_ENC_PAN,

    X32_ENC_BUS_SEND_1,
    X32_ENC_BUS_SEND_2,
    X32_ENC_BUS_SEND_3,
    X32_ENC_BUS_SEND_4,

    X32_ENC_ENCODER1,
    X32_ENC_ENCODER2,
    X32_ENC_ENCODER3,
    X32_ENC_ENCODER4,
    X32_ENC_ENCODER5,
    X32_ENC_ENCODER6,

    // only X32 Full and X32 Core
    X32_ENC_ASSIGN_1,
    // only X32 Full and X32 Core
    X32_ENC_ASSIGN_2,
    // only X32 Full
    X32_ENC_ASSIGN_3,
    // only X32 Full
    X32_ENC_ASSIGN_4,

    // only X32 Rack
    X32_ENC_CHANNEL_SELECT,
    // only X32 Rack
    X32_ENC_CHANNEL_LEVEL,
    // only X32 Rack
    X32_ENC_MAIN_LEVEL,

} X32_ENC;

// Mode of the Banking
typedef enum {
    // Standard Layout like X32 Original
    X32_SURFACE_MODE_BANKING_X32,

    // User Layout
    X32_SURFACE_MODE_BANKING_USER,
} X32_SURFACE_MODE_BANKING;

typedef enum {
    X32_BOARD_MAIN =    0x00,
    X32_BOARD_L =       0x04,
    X32_BOARD_M =       0x05, // only X32 Full
    X32_BOARD_R =       0x08,
} X32_BOARD;

enum class X32_MODEL {
    NONE,
    FULL,
    COMPACT,
    PRODUCER,
    RACK,
    CORE
};

enum class X32_PAGE :int {
    NONE,
    HOME,
        // sub-pages of home
        CONFIG,
        GATE,
        EQ,
        COMPRESSOR,
    METERS,
        // sub-pages of meters?
    ROUTING,
        // sub-pages of routing
        ROUTING_FPGA,
        ROUTING_DSP1,
        ROUTING_DSP2,
    SETUP,
        // sub-pages of setup
        SETUP_CARD,
    LIBRARY,
    EFFECTS,
    MUTE_GRP,
    UTILITY
};

enum class X32_VCHANNELTYPE {
    NONE,
    NORMAL,
    AUX,
    FXRET,
    BUS,
    MATRIX,
    DCA,
    MAIN,
    MAINSUB,
    SPECIAL
};

enum class X32_VCHANNEL_BLOCK : int {
    NONE = -1,
    NORMAL = 0,
    AUX = 32,
    FXRET = 40,
    BUS = 48,
    MATRIX = 64,
    SPECIAL = 70,
    MAINSUB = 71,
    DCA = 72,
    MAIN = 80    
};

enum class X32_VCHANNEL_BLOCK_SIZE : int {
    NONE = 0,
    NORMAL = 32,
    AUX = 8,
    FXRET = 8,
    BUS = 16,
    MATRIX = 6,
    DCA = 8,
    MAIN = 1,
    MAINSUB = 1,
    SPECIAL = 1
};

enum class MP_UOM {
    NONE,
    DB, // dB
    DBFS, // dB Full Scale
    MS, // Milliseconds
    SECONDS, // Seconds
    HZ, // Hertz
    KHZ, // Kilohertz
    PERCENT // Percent
};

enum class MP_VALUE_TYPE {
    FLOAT,
    UINT,
    INT,
    BOOL,
    STRING
};

enum class MP_CAT {
    NONE,
    SETTING,
    STATE,
    CHANNEL,
    FX
};

/// @brief Mixerparameter ID
enum class MP_ID {
    NONE,

    // Settings

    LCD_CONTRAST,
    LED_BRIGHTNESS,
    DISPLAY_BRIGHTNESS,
    SAMPLERATE,
    CARD_NUMBER_OF_CHANNELS,

    // Routing

    // TODO: Define Routingparameter
    ROUTING_TODO,

    // State

    SELECTED_CHANNEL,
    ACTIVE_PAGE,
    BANKING_EQ,
    BANKING_INPUT,
    BANKING_BUS,

    // Channel

    CHANNEL_SOURCE,
    CHANNEL_NAME,
    CHANNEL_NAME_INTERN,
    CHANNEL_COLOR,
    CHANNEL_COLOR_INVERTED,
    CHANNEL_GAIN,
    CHANNEL_PANORAMA,
    CHANNEL_VOLUME,
    CHANNEL_SELECTED,
    CHANNEL_MUTE,
    CHANNEL_SOLO,
    CHANNEL_PHASE_INVERT,
    CHANNEL_PHANTOM,

    CHANNEL_GATE_TRESHOLD,
    CHANNEL_GATE_RANGE,
    CHANNEL_GATE_ATTACK,
    CHANNEL_GATE_HOLD,
    CHANNEL_GATE_RELEASE,
    
    CHANNEL_DYNAMICS_TRESHOLD,
    CHANNEL_DYNAMICS_RATIO,
    CHANNEL_DYNAMICS_MAKEUP,
    CHANNEL_DYNAMICS_ATTACK,
    CHANNEL_DYNAMICS_HOLD,
    CHANNEL_DYNAMICS_RELEASE,

    // TODO define EQ Mixerparamters
    CHANNEL_EQ_TODO,

    // FX

    FX_REVERB_ROOMSIZE,
    FX_REVERB_RT60,
    FX_REVERB_LPFREQ,
    FX_REVERB_DRY,
    FX_REVERB_WET,

    FX_CHORUS_DEPTH_A,
    FX_CHORUS_DEPTH_B,
    FX_CHORUS_DELAY_A,
    FX_CHORUS_DELAY_B,
    FX_CHORUS_PHASE_A,
    FX_CHORUS_PHASE_B,
    FX_CHORUS_FREQ_A,
    FX_CHORUS_FREQ_B,
    FX_CHORUS_MIX,

    FX_TRANSIENTSHAPER_FAST,
    FX_TRANSIENTSHAPER_MEDIUM,
    FX_TRANSIENTSHAPER_SLOW,
    FX_TRANSIENTSHAPER_ATTACK,
    FX_TRANSIENTSHAPER_SUSTAIN,
    FX_TRANSIENTSHAPER_DELAY,

    FX_OVERDRIVE_PREGAIN,
    FX_OVERDRIVE_Q,
    FX_OVERDRIVE_HPF_INPUTFREQ,
    FX_OVERDRIVE_LPF_INPUTFREQ,
    FX_OVERDRIVE_LPF_OUTPUTFREQ,

    FX_DELAY_DELAY_A,
    FX_DELAY_DELAY_B,

    FX_MULTIBANDCOMPRESOR_L_BAND1_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND2_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND3_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND4_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND5_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND1_RATIO,
    FX_MULTIBANDCOMPRESOR_L_BAND2_RATIO,
    FX_MULTIBANDCOMPRESOR_L_BAND3_RATIO,
    FX_MULTIBANDCOMPRESOR_L_BAND4_RATIO,
    FX_MULTIBANDCOMPRESOR_L_BAND5_RATIO,
    FX_MULTIBANDCOMPRESOR_L_BAND1_ATTACK,
    FX_MULTIBANDCOMPRESOR_L_BAND2_ATTACK,
    FX_MULTIBANDCOMPRESOR_L_BAND3_ATTACK,
    FX_MULTIBANDCOMPRESOR_L_BAND4_ATTACK,
    FX_MULTIBANDCOMPRESOR_L_BAND5_ATTACK,
    FX_MULTIBANDCOMPRESOR_L_BAND1_HOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND2_HOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND3_HOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND4_HOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND5_HOLD,
    FX_MULTIBANDCOMPRESOR_L_BAND1_RELEASE,
    FX_MULTIBANDCOMPRESOR_L_BAND2_RELEASE,
    FX_MULTIBANDCOMPRESOR_L_BAND3_RELEASE,
    FX_MULTIBANDCOMPRESOR_L_BAND4_RELEASE,
    FX_MULTIBANDCOMPRESOR_L_BAND5_RELEASE,
    FX_MULTIBANDCOMPRESOR_L_BAND1_MAKEUP,
    FX_MULTIBANDCOMPRESOR_L_BAND2_MAKEUP,
    FX_MULTIBANDCOMPRESOR_L_BAND3_MAKEUP,
    FX_MULTIBANDCOMPRESOR_L_BAND4_MAKEUP,
    FX_MULTIBANDCOMPRESOR_L_BAND5_MAKEUP,
    FX_MULTIBANDCOMPRESOR_R_BAND1_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND2_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND3_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND4_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND5_THRESHOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND1_RATIO,
    FX_MULTIBANDCOMPRESOR_R_BAND2_RATIO,
    FX_MULTIBANDCOMPRESOR_R_BAND3_RATIO,
    FX_MULTIBANDCOMPRESOR_R_BAND4_RATIO,
    FX_MULTIBANDCOMPRESOR_R_BAND5_RATIO,
    FX_MULTIBANDCOMPRESOR_R_BAND1_ATTACK,
    FX_MULTIBANDCOMPRESOR_R_BAND2_ATTACK,
    FX_MULTIBANDCOMPRESOR_R_BAND3_ATTACK,
    FX_MULTIBANDCOMPRESOR_R_BAND4_ATTACK,
    FX_MULTIBANDCOMPRESOR_R_BAND5_ATTACK,
    FX_MULTIBANDCOMPRESOR_R_BAND1_HOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND2_HOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND3_HOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND4_HOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND5_HOLD,
    FX_MULTIBANDCOMPRESOR_R_BAND1_RELEASE,
    FX_MULTIBANDCOMPRESOR_R_BAND2_RELEASE,
    FX_MULTIBANDCOMPRESOR_R_BAND3_RELEASE,
    FX_MULTIBANDCOMPRESOR_R_BAND4_RELEASE,
    FX_MULTIBANDCOMPRESOR_R_BAND5_RELEASE,
    FX_MULTIBANDCOMPRESOR_R_BAND1_MAKEUP,
    FX_MULTIBANDCOMPRESOR_R_BAND2_MAKEUP,
    FX_MULTIBANDCOMPRESOR_R_BAND3_MAKEUP,
    FX_MULTIBANDCOMPRESOR_R_BAND4_MAKEUP,
    FX_MULTIBANDCOMPRESOR_R_BAND5_MAKEUP,

    FX_MULTIBANDCOMPRESOR_L_FREQ1,
    FX_MULTIBANDCOMPRESOR_L_FREQ2,
    FX_MULTIBANDCOMPRESOR_L_FREQ3,
    FX_MULTIBANDCOMPRESOR_L_FREQ4,

    FX_MULTIBANDCOMPRESOR_R_FREQ1,
    FX_MULTIBANDCOMPRESOR_R_FREQ2,
    FX_MULTIBANDCOMPRESOR_R_FREQ3,
    FX_MULTIBANDCOMPRESOR_R_FREQ4,
    FX_MULTIBANDCOMPRESOR__START = FX_MULTIBANDCOMPRESOR_L_BAND1_THRESHOLD, // start of section (for looping)
    FX_MULTIBANDCOMPRESOR__END = FX_MULTIBANDCOMPRESOR_R_FREQ4, // end of section (for looping)

    FX_DYNAMICEQ_BAND1_TYPE,
    FX_DYNAMICEQ_BAND2_TYPE,
    FX_DYNAMICEQ_BAND3_TYPE,
    FX_DYNAMICEQ_BAND1_FREQ,
    FX_DYNAMICEQ_BAND2_FREQ,
    FX_DYNAMICEQ_BAND3_FREQ,
    FX_DYNAMICEQ_BAND1_STATICGAIN,
    FX_DYNAMICEQ_BAND2_STATICGAIN,
    FX_DYNAMICEQ_BAND3_STATICGAIN,
    FX_DYNAMICEQ_BAND1_MAXDYNGAIN,
    FX_DYNAMICEQ_BAND2_MAXDYNGAIN,
    FX_DYNAMICEQ_BAND3_MAXDYNGAIN,
    FX_DYNAMICEQ_BAND1_Q,
    FX_DYNAMICEQ_BAND2_Q,
    FX_DYNAMICEQ_BAND3_Q,
    FX_DYNAMICEQ_BAND1_THRESHOLD,
    FX_DYNAMICEQ_BAND2_THRESHOLD,
    FX_DYNAMICEQ_BAND3_THRESHOLD,
    FX_DYNAMICEQ_BAND1_RATIO,
    FX_DYNAMICEQ_BAND2_RATIO,
    FX_DYNAMICEQ_BAND3_RATIO,
    FX_DYNAMICEQ_BAND1_ATTACK,
    FX_DYNAMICEQ_BAND2_ATTACK,
    FX_DYNAMICEQ_BAND3_ATTACK,
    FX_DYNAMICEQ_BAND1_RELEASE,
    FX_DYNAMICEQ_BAND2_RELEASE,
    FX_DYNAMICEQ_BAND3_RELEASE
};

enum class FX_TYPE : int {
    NONE = -1,
    REVERB = 0,
    CHORUS = 1,
    TRANSIENTSHAPER = 2,
    OVERDRIVE = 3,
    DELAY = 4,
    MULTIBANDCOMPRESOR = 5,
    DYNAMICEQ = 6
};

enum class X32_COLOR : int {
    BLACK = 0,
    RED = 1,
    GREEN = 2,
    YELLOW = 3,
    BLUE = 4,
    PINK = 5,
    CYAN = 6,
    WHITE = 7
};